// <auto-generated />
using Kongsli.UrlShortener.Original.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kongsli.UrlShortener.Original.Migrations
{
    [DbContext(typeof(ShortUrlDbContext))]
    partial class ShortUrlContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.9");

            modelBuilder.Entity("Kongsli.UrlShortener.Models.ShortUrl", b =>
                {
                    b.Property<string>("ShortPath")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEmpty")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ShortPath");

                    b.ToTable("ShortUrls");
                });
#pragma warning restore 612, 618
        }
    }
}
